In [16]:
import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.models import load_model
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical
import numpy as np

## Read the Data

In [12]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [13]:
x_train

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [14]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [15]:
x_train[0].shape

(28, 28)

In [17]:
x_train = x_train / 255.0
x_test = x_test / 255.0

In [18]:
np.unique(y_train)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [19]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [20]:
to_categorical(y_train)[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

In [21]:
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

## Train Model

In [22]:
model=Sequential([
    tf.keras.layers.Input(shape=x_train[0].shape),
    Flatten(),
    Dense(128,activation='relu'),
    Dense(10,activation='softmax')
])

In [23]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy']
)

In [24]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 784)               0         
                                                                 
 dense (Dense)               (None, 128)               100480    
                                                                 
 dense_1 (Dense)             (None, 10)                1290      
                                                                 
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________


In [27]:
model.fit(x_train,y_train,epochs=5, validation_split=0.2)

Epoch 1/5
1500/1500 [==============================] - 3s 2ms/step - loss: 0.0759 - accuracy: 0.9766 - val_loss: 0.0731 - val_accuracy: 0.9775
Epoch 2/5
1500/1500 [==============================] - 3s 2ms/step - loss: 0.0549 - accuracy: 0.9835 - val_loss: 0.0681 - val_accuracy: 0.9781
Epoch 3/5
1500/1500 [==============================] - 3s 2ms/step - loss: 0.0419 - accuracy: 0.9876 - val_loss: 0.0648 - val_accuracy: 0.9798
Epoch 4/5
1500/1500 [==============================] - 3s 2ms/step - loss: 0.0348 - accuracy: 0.9893 - val_loss: 0.0791 - val_accuracy: 0.9761
Epoch 5/5
1500/1500 [==============================] - 3s 2ms/step - loss: 0.0268 - accuracy: 0.9917 - val_loss: 0.0630 - val_accuracy: 0.9805


## Save Model

In [ ]:
model.save("keras_model.keras")

## Load Model

In [31]:
keras_model = load_model("keras_model.keras")

In [32]:
model.evaluate(x_test,y_test)

313/313 [==============================] - 1s 1ms/step - loss: 0.0720 - accuracy: 0.9778


[0.07202880084514618, 0.9778000116348267]

In [34]:
keras_model.evaluate(x_test,y_test)

313/313 [==============================] - 0s 1ms/step - loss: 0.0720 - accuracy: 0.9778


[0.07202880084514618, 0.9778000116348267]